[package]
name = "deputy"
version = "0.1.0"
edition = "2024"
description = "Agentic CLI tool"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
indicatif = "0.17.9"
rig-core = { version = "0.13.0", features = ["all"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.46.0", features = ["full"] }